### ISSUE TITLE
The download quota for these files has been exceeded

### ISSUE THREAD

**Issue by mgrankin** [sberbank-ai/ru-gpts#1]
Thank you so much for an amazing job. It’s a great pleasure to see Sber commitment to open AI research.

May I ask you to rehost models using more friendly method. I get the message “The download quota for these files has been exceeded”. A direct http url or torrent client magnet link is better for sharing large files.

**Comment by mgrankin** [comment]
AWS works as well

**Comment by king-menin** [comment]
If you cannot download the checkpoint, try adding it to your google drive following this [issue](https://www.geekrar.com/fix-bypass-google-drive-download-limit-error/)

**Comment by mgrankin** [comment]
Thank you for the suggestion. It's in my drive, I've made a copy of it and there is plenty of free space. But still “The download quota for these files has been exceeded”.

**Comment by mgrankin** [comment]
Thank you for an alternative download method.
