### ISSUE TITLE
reason for relicense to MIT?

### ISSUE THREAD

**Issue by bobuk** [sberbank-ai/ru-gpts#10]
If I understand correctly, according to the LICENSE file the project is given under the MIT license. However, most of the code is inherited from the GPT2 project produced by Nvidia under the Apache license.

Let me remind you two rules of Apache 1. license change requires agreement with all previous developers of the project 2. making changes to files under the Apache license requires an indication of what exactly was changed and for what purpose (a notification must be added stating that changes have been made to that file)

Is it possible to know what such an attempt to relicense was made for?

**Comment by king-menin** [comment]
Thank you for your issue. It was our mistake. We update LICENSE file.

**Comment by bobuk** [comment]
Thank you for the quick and adequate decision.

When/if you have time, try to describe the changes you made to files written by Nvidia as required by the Apache License. As a first answer, just move the commit message inside the files or into a separate file with a description of the changes, it's a common practice for such edits.

Thanks again for the amazing work, you are doing a colossal and important job, please continue!
