### ISSUE TITLE
Google Colab incoming?

### ISSUE THREAD

**Issue by fen0s** [sberbank-ai/ru-gpts#11]
We'll have a colab notebook for it soon?

**Comment by king-menin** [comment]
I had just add google colab for generation [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sberbank-ai/ru-gpts/blob/master/examples/ruGPT3_generation_example.ipynb)

For training we will add rugpt3small soon.
