### ISSUE TITLE
Is it possible to train models in Google Colab?

### ISSUE THREAD

**Issue by Markfryazino** [sberbank-ai/ru-gpts#13]
I've tried training both ruGPT3Large and ruGPT2Large in Google Colab using P100 as GPU. However, cuda runs out of memory at the very beginning of the training. Is it possible to use Google Colab for training models and if yes, how it can be done? A working example would be very helpful.

**Comment by king-menin** [comment]
I had just add google colab for generation [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sberbank-ai/ru-gpts/blob/master/examples/ruGPT3_generation_example.ipynb)

For training we will add rugpt3small soon.
