### ISSUE TITLE
Буква Н в выводе

### ISSUE THREAD

**Issue by AlexRMU** [sberbank-ai/ru-gpts#14]
В generate_ruGPT3Large.sh и generate_transformers.py каждый вывод начинается с Н. Мне кажется, что так не было задумано изначально.

> Context >>> на словах ты лев толстой
10/23/2020 14:45:27 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
Hна словах ты лев толстой,
		А на деле — как все мы.
		А на самом деле 
Context >>> на словах ты лев толстой
10/23/2020 14:45:33 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
Hна словах ты лев толстой и пушистый!  Я не могу тебя отпустить! 

> - Я люблю тебя, - прошептал 
Context >>> Hна словах ты лев толстой и пушистый!  Я не могу тебя отпустить!
10/23/2020 14:45:44 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
HHна словах ты лев толстой и пушистый!  Я не могу тебя отпустить!  Ты будешь моей!  Я хочу, чтоб мы были счастливы, и не важно, сколько теб
Context >>> privet
10/23/2020 14:46:00 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
Hprivet-rodina.ru/...✂ http://rodinavet.ru/...✂ http://r
Context >>> лол
10/23/2020 14:46:08 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
Hлол, как я уже говорил, была в том числе и частью «памятника» — 
Context >>> ыеврвыкр
10/23/2020 14:46:21 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
Hыеврвыкр
Context >>> Hпривет
10/23/2020 14:50:47 - WARNING - transformers.modeling_utils -   Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
ruGPT:
HHпривет!

**Comment by king-menin** [comment]
Спасибо за замечание. Fixed. Попробуйте остановить колаб ноутбук и пройти заново по ячейкам (проверьте что скачался новый файл). Проблема была вызвана как ни странно os.system("clear") и в колабе произошло неверное отображение (появилась Н)
