### ISSUE TITLE
num_samples error?

### ISSUE THREAD

**Issue by fen0s** [sberbank-ai/ru-gpts#15]
I'm trying to finetune GPT-2 Large and I get that error:
```
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
What is that? Googling says that dataset is missing, but i've checked twice, and the path is absolute correct. Tried with both absolute and non-absolute path.

**Comment by king-menin** [comment]
What script do you use? in transformers we can get this error if block_size > len(tokens_in_data).

**Comment by king-menin** [comment]
if you use our script `pretrain_transformers.py` try to remove this line: https://github.com/sberbank-ai/ru-gpts/blob/8e7c92b44610756cbb99acaf86a9e8344b9a44c0/pretrain_transformers.py#L56
and check block_size below.
also check `tokenizer.max_len==1024` and see line: https://github.com/sberbank-ai/ru-gpts/blob/8e7c92b44610756cbb99acaf86a9e8344b9a44c0/pretrain_transformers.py#L698
you can try to remove.

**Comment by fen0s** [comment]
It worked for resolving num_samples. Colab doesn't have enough memory to finetune it though... Thanks for help anyways!

**Comment by Dmitriuso** [comment]
hey,
I was trying to fine-tune the GPT2 model, too, and came across the same problem as @fen0s . I got the idea that `block_size` should be < `len(tokens_in_data)`. Still, I didn't quite get how one can make sure this condition is respected: how one makes sure that `tokenizer.max_len==1024`... could you explain it step-by-step, please?
