### ISSUE TITLE
Dataset collaboration

### ISSUE THREAD

**Issue by mgrankin** [sberbank-ai/ru-gpts#19]
Hello, 

Thank you for the high quality pre-trained model, it's super easy to deploy and use.

As you may know there is an ongoing community driven effort to replicate GPT3 with 175B parameters. A part of the project is building the dataset. The version 1 of the dataset is focused on English and is almost ready. The next goal is a fully-multilingual, 10TiB text dataset.

https://github.com/EleutherAI/The-Pile

Would you mind sharing yours dataset, so it can be part of the project?

**Comment by king-menin** [comment]
Hello!
We apologize for the long answer. Our team discussed the posibilities and restrictions of data rights and license agreements. We are not ready to publish our data yet, but it would be cool to communicate in person and discuss ideas and datasets, for instance, in zoom meeting. Please write to login-const@mail.ru to clarify the details. Thanks! Our team will be happy to collaborate with you ☺️

**Comment by mgrankin** [comment]
Hello and thank you for your reply. Looking forward to collaborating with your team!
