### ISSUE TITLE
Broken encoding of vocab.json

### ISSUE THREAD

**Issue by kniazevgeny** [sberbank-ai/ru-gpts#24]
I was fine-tuning ruGPT3-Medium for QA, but there was some problems with training. After setting 50 epochs with small dataset (to be sure that I can fine-tune model) I found that the only answer was in english. 
![image](https://user-images.githubusercontent.com/41857481/97778192-9a1b9a80-1b86-11eb-9bff-f5d5683d69b8.png)
So I looked what was in the [vocab.json ](https://s3.amazonaws.com/models.huggingface.co/bert/sberbank-ai/rugpt3small_based_on_gpt2/vocab.json). I found lots of broken (?) symbols with strange encoding. 
![image](https://user-images.githubusercontent.com/41857481/97778286-642ae600-1b87-11eb-9bd0-af926caddf78.png)
 I tried to change it to _windows1252_, _windows 1251_ and _iso8859-5_ but there was no result. Can you please explain me what I did wrong or just fix the vocab.json

**Comment by fen0s** [comment]
That's something that weirded me off, too. If you try to train it, you may also look at features file which contains lots of broken encoding. I've mentioned this in my issue, too. Seems like it's somewhat readable for the generator, though? Are you sure you set your encoding for output to UTF-8?

**Comment by kniazevgeny** [comment]
It could be readable for generator, but in this case there should be some preprocessing of my training data. If so, that would be strange. 
As for encoding of the file, yeah, it's set to UTF-8 (and you can see it in the right bottom corner). By the way, there's a link to vocab.json above. 
And yes, I might look at features file, but I'm not really familiar with this. So if you gave me some instructions, I'd try.

**Comment by kniazevgeny** [comment]
I reviewed the source code and realized that I used custom tokenizer. Then I replaced it with tokenizer from transformers library and got my human-readable answers converted into the text similar to shown above. Now I'm testing whether it would work
![image](https://user-images.githubusercontent.com/41857481/97809386-974fa100-1c7d-11eb-8a6b-9b7dbc90bef9.png)

**Comment by fen0s** [comment]
Yeah, I have no idea then. You might look at how data is preproccessed for GPT-3 in readme file, if you didn't preproccess your dataset. GPT-2 also needs dataset preproccessed, though it's not listed in the readme.
Seems like a really raw model implementation tbh.

**Comment by kniazevgeny** [comment]
I've just tested **GPT2Tokenizer from transformers**, and now I see that the problem was in my custom tokenizer. So vocab.json seems to be ok, and it's encoding is all right
