### ISSUE TITLE
Can't load a model from path.

### ISSUE THREAD

**Issue by rogachevai** [sberbank-ai/ru-gpts#29]
I use a path to a downloaded model instead of using it's name to avoid downloading. Unfortunately, it doesn't work for me.

`/content/generate_transformers.py in predict(model_name, start, length_, temperature_)
    191         raise KeyError("the model {} you specified is not supported. You are welcome to add it and open a PR :)")
    192 
--> 193     tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path)
    194     model = model_class.from_pretrained(args.model_name_or_path)
    195     model.to(args.device)

/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py in from_pretrained(cls, *inputs, **kwargs)
    391 
    392         """
--> 393         return cls._from_pretrained(*inputs, **kwargs)
    394 
    395     @classmethod

/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py in _from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
    542         # Instantiate tokenizer.
    543         try:
--> 544             tokenizer = cls(*init_inputs, **init_kwargs)
    545         except OSError:
    546             raise OSError(

/usr/local/lib/python3.6/dist-packages/transformers/tokenization_gpt2.py in __init__(self, vocab_file, merges_file, errors, unk_token, bos_token, eos_token, **kwargs)
    147         **kwargs
    148     ):
--> 149         super().__init__(bos_token=bos_token, eos_token=eos_token, unk_token=unk_token, **kwargs)
    150         self.max_len_single_sentence = (
    151             self.max_len

/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py in __init__(self, max_len, **kwargs)
    335                     assert isinstance(value, (list, tuple)) and all(isinstance(t, str) for t in value)
    336                 else:
--> 337                     assert isinstance(value, str)
    338                 setattr(self, key, value)
    339 `

The path looks like `/content/gdrive/MyDrive/rugpt3small_based_on_gpt2/gpt3_small_ppl_21_8/`

It also doesn't run if I use a path to the .tar
So, any solutions for using downloaded models? Thanks.

**Comment by king-menin** [comment]
version of transformers is 2.8.0? Can you give us code of starting script? Do you use something like [this](https://colab.research.google.com/github/sberbank-ai/ru-gpts/blob/master/examples/ruGPT3_generation_example.ipynb)

**Comment by king-menin** [comment]
I had just tested example on colab.
I download files from hf, move to model directory and run generation. Check this [here](https://colab.research.google.com/drive/1CTEAwVEIa_1drzCX0AsOsIgLG4eBwafp?usp=sharing)

**Comment by rogachevai** [comment]
Well, it works, even if I store all the files from s3 on gdrive. So, looks like an issue with the files from the [link](https://drive.google.com/file/d/19dyhhayJSVJpVPwPzqLRIdCtOddvkzJ4/view) provided in the repo? Can you test the model from the link locally? 
Thanks
