### ISSUE TITLE
Суммаризация

### ISSUE THREAD

**Issue by seregadgl** [sberbank-ai/ru-gpts#33]
Подскажите, как ru-gpts можно использовать для суммаризации, либо как ее обучить для этих целей. Спасибо

**Comment by king-menin** [comment]
Полагаю надо дообучить. Можно подавать на дообучение тексты формата: Text: <text> Summary: <summary>

**Comment by seregadgl** [comment]
> Полагаю лучше дообучить. Можно подавать на дообучение тексты формата: Text: Summary:
