### ISSUE TITLE
What is the purpose of weights named transformer.h.N.attn.masked_bias?

### ISSUE THREAD

**Issue by drunkinlove** [sberbank-ai/ru-gpts#35]
I'm trying to use the small GPT-3 checkpoint for finetuning using the DialoGPT repository, but it says the "transformer.h.N.attn.masked_bias" are unexpected. What layers do these weights refer to?

**Comment by king-menin** [comment]
Please give more info about your code and transformers version

**Comment by drunkinlove** [comment]
The DialoGPT repo uses some old version of the GPT2LMHeadModel (possibly custom): https://github.com/microsoft/DialoGPT/blob/master/lsp_model/modeling_gpt2.py#L72

These weights have a fixed value of -10000, what operation are they a part of?
I'm able to finetune the model after I delete the weights, but I can't help wondering how much it'll affect the learned structure of the model

**Comment by king-menin** [comment]
We support only megatron and huggingface interfaces. For consistency use code in or repo

**Comment by 1LISA2** [comment]
![images (2)](https://user-images.githubusercontent.com/103248540/188131463-3ed2b285-a88a-43d5-aece-0fc0a0e3dd3d.jpeg)
understand????
