### ISSUE TITLE
не сохраняется pytorch_model.bin после половины итераций

### ISSUE THREAD

**Issue by concrete13377** [sberbank-ai/ru-gpts#44]
Запустил дообучение на собственном датасете, все работает, но в чекпоинтах не всегда сохраняется pytorch_model.bin.
Например чекпоинт 10к итераций с моделью 
![image](https://user-images.githubusercontent.com/32034827/111025576-0c826e00-83f6-11eb-96e2-fe611244e76b.png)
а 11к итераций уже без модели 
![image](https://user-images.githubusercontent.com/32034827/111025583-1ad08a00-83f6-11eb-911f-fc3a56203f3c.png)

В чем может быть проблема?

**Comment by king-menin** [comment]
Не сталкивались с такой проблемой, полагаю вы учите скриптом pretrain_transformers.py?
