### ISSUE TITLE
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)

### ISSUE THREAD

**Issue by Chertoganov** [sberbank-ai/ru-gpts#45]
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)

how to solve this error in google colab?
как решить эту проблему в google colab?

**Comment by dmitriypereverza** [comment]
это должно помочь pip install torch==1.4.0

**Comment by CamilleSchr** [comment]
Hi, by doing pip install torch==1.4.0, I have this error : 
ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==1.4.0

Can you help me please ?

**Comment by king-menin** [comment]
install torch 1.4 specified for cuda
