### ISSUE TITLE
Чувствительные данные в обучающем корпусе

### ISSUE THREAD

**Issue by albatross668** [sberbank-ai/ru-gpts#52]
Здравствуйте.
Скажите, пожалуйста, обучающий корпус каким-нибудь образом очищался от чувствительных данных? Или при обучении использовались какие-то методы, мешающие получению непреднамеренно запомненных моделью данных? Например, методы дифференциальной конфиденциальности?
Просто не хотелось бы, чтобы при генерации текста кто-то из пользователей получил ответ, содержащий персональные данные какой-нибудь личности.
Спасибо.

**Comment by king-menin** [comment]
При обучении использовались открытые данные, собранные из интернета, например русская часть из c4 корпуса. Никаких методов про анонимизацию не использовались
