### ISSUE TITLE
Не получается запустить скрипты на torch 1.8.0

### ISSUE THREAD

**Issue by delaryc** [sberbank-ai/ru-gpts#53]
Пытаюсь запустить скрипты но выходит ошибка ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' Погуглив, понял, что нужна версия torch 1.4.0 но ее уже нет, а на 1.8.0 такая ошибка, можете обновить скрипты до актуальных версий? Или как быть в такой ситуации?

**Comment by nicoth-in** [comment]
This issue is related to the Transformers library.
Use newer version, like `4.3.0`
(In colab, replace  to `!pip3 install transformers==4.3.0`)

https://github.com/huggingface/transformers/issues/9060#issuecomment-791673571
https://github.com/huggingface/transformers/pull/8979

**Comment by nicoth-in** [comment]
Readme/examples update suggestion #54

**Comment by king-menin** [comment]
please use old version of transformers. For Now we don't adapt our models for newest version. we apologize for the inconvenience

**Comment by nicoth-in** [comment]
The problem is that the old transformers uses old pytorch, and old version of pytorch is no longer supported and not in PIP, so it is generaly breaks all the examples and adds trubleshooting steps for newcommers. Not sure how new versions will affect stability, but it at least worked for me.
