### ISSUE TITLE
Integration with wandb

### ISSUE THREAD

**Issue by alienspaceman** [sberbank-ai/ru-gpts#55]
Is there a possibility to add an integration with wandb? Or maybe it works already but I can't figure out how. Please, help

**Comment by king-menin** [comment]
Sorry, we are not planning any work in this area

**Comment by 1LISA2** [comment]
![images (1)](https://user-images.githubusercontent.com/103248540/188130709-9184a912-3e01-41a9-afc2-2cb9e55f3c90.jpeg)
123？？？？？？？？？
