### ISSUE TITLE
CPU offload режим для GPT3XL

### ISSUE THREAD

**Issue by exelents** [sberbank-ai/ru-gpts#59]
Добрый день. 
Недавно при попытке файнтюнить самую большую GPT3XL столкнулся с ошибкой нехватки памяти. Попытался в конфиге deepspeed включить режим cpu_offload и обломался - выдаётся ошибка, см стек по ссылке:
https://gist.github.com/exelents/dd64ddd745bfa732a809a6b3e9af678d
Вопрос - что нужно сделать чтоб данная модель завелась в режиме cpu offload и возможно ли  это вообще?

**Comment by exelents** [comment]
Я дико извиняюсь, похоже сам нашел как забороть проблему.
В файле pretrain_gpt3.py просто заменил оптимизатор:
```
# from apex.optimizers import FusedAdam as Adam
from deepspeed.ops.adam import DeepSpeedCPUAdam as Adam
```
Надеюсь больше не будет подводных камней.

**Comment by AlexanderKozhevin** [comment]
@exelents добрый день. 
не могли бы подсказать,  я файл pretrain_gpt3 изменил. 
Но ошибку все равно получаю. " module 'apex' has no attribute 'optimizers'"

На этапе теста
```
import deepspeed.ops.sparse_attention.sparse_attn_op
```

**Comment by exelents** [comment]
Не могли бы вы привести полный стек ошибки? А заодно какую команду вы запускаете?

**Comment by Artyrm** [comment]
@exelents в Colab это помогло мне продвинуться дальше, но теперь вылетает с такой ошибкой:

```
 > number of parameters on model parallel rank 0: 1315737600
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node 7507dafadf1d exited on signal 4 (Illegal instruction).
--------------------------------------------------------------------------
```

А у вас без проблем всё заработало?

**Comment by exelents** [comment]
на счёт памяти - не подскажу, у меня-то как раз памяти много.

**Comment by Artyrm** [comment]
А насколько много?

В Colab сейчас у меня GPU Tesla P100-PCIE 16GB и соответственно 24GB ОЗУ.
Дотренировывать пытаюсь на жалких 100кБ текста.

Как-то досадно, ведь вроде бы выложен Colab ноутбук как раз с примером, и у меня вроде максимум того, что возможно на Colab...

**Comment by exelents** [comment]
Очень много. Б/у серверное железо с кучей оперы, гораздо больше чем на коллабе. Видюха RTX3090 на ней соответственно 24 ГБ памяти. Тренируете на deepspeed? Попробуйте конфиг дипспида поставить тот который я вам сейчас прикреплю.
[gpt3_xl_sparse_2048_offload.json.zip](https://github.com/sberbank-ai/ru-gpts/files/6902697/gpt3_xl_sparse_2048_offload.json.zip)

**Comment by Artyrm** [comment]
Да, на Deepspeed, иначе бы offload в ОЗУ не получился (хотя я сейчас смотрю, есть вроде флаги отдельные у трейнера, например 
```
  cpu_optimizer ................ False
  cpu_torch_adam ............... False
```

К сожалению, не помог конфиг. Для будущих поколений приложу что добавлено в сравнении с моим.

![image](https://user-images.githubusercontent.com/21180686/127545805-77785b5c-976e-4c05-bc86-292834acdf85.png)
