### ISSUE TITLE
Is it ruGPT3Large or Setup ruGPT2Large

### ISSUE THREAD

**Issue by jibozogsotron** [sberbank-ai/ru-gpts#6]
Why is it referred by Sberbank as ruGPT-3 everywhere including readme file, but the model itself is named gpt2_large_bbpe_v50
That's correct? We should be using gpt2_large_bbpe_v50? this reference as gpt2 and gpt3 is confusing.

**Comment by king-menin** [comment]
Sorry, thats  is confusing. This is gpt2 model
