### ISSUE TITLE
RuntimeError: CUDA: Error- invalid ptx

### ISSUE THREAD

**Issue by Pro100rus32** [sberbank-ai/ru-gpts#62]
Ну изначально вообще ничего не работало, пока не увидел #60, потом всё шло +- спокойно
![image](https://user-images.githubusercontent.com/64806740/120311104-c85d8600-c2df-11eb-9964-31a14d631767.png)

Но в итоге я встретил опять ошибку.
![image](https://user-images.githubusercontent.com/64806740/120311036-b4198900-c2df-11eb-88a4-1805403f4a13.png)

Один вопрос буквально: Это вообще хоть кто - то тестировал?) Впервые встречаю так много ошибок. Больше похоже на заброшенный репозиторий (тогда зачем собственно публиковать статьи и хвастаться, если вы не поддерживаете репо на данный момент?) Грустненько однако...

**Comment by king-menin** [comment]
Неверно установили triton версию. вам надо удалить deepspeed и тритон и попробуйте следующее:

`!rm -rf /tmp/DeepSpeed`

`!pip install triton==0.2.3`

`cd /tmp && git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed/ && git checkout ff58fa7e5a4f637a21d11daad0192683fe50ed15 && pip uninstall -y typing && pip install cpufeature && DS_BUILD_CPU_ADAM=1 DS_BUILD_SPARSE_ATTN=1 /tmp/DeepSpeed/install.sh -n && pip install typing`

`pip install transformers==3.5.1`

**Comment by Pro100rus32** [comment]
```
[Errno 2] No such file or directory: '/tmp && git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed/ && git checkout ff58fa7e5a4f637a21d11daad0192683fe50ed15 && pip uninstall -y typing && pip install cpufeature && DS_BUILD_CPU_ADAM=1 DS_BUILD_SPARSE_ATTN=1 /tmp/DeepSpeed/install.sh -n && pip install typing'
/content
```

**Comment by Pro100rus32** [comment]
> Неверно установили версию triton. вам надо удалить deepspeed и тритон и другое следующее:
> 
> `!rm -rf /tmp/DeepSpeed`
> 
> `!pip install triton==0.2.3`
> 
> `cd /tmp && git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed/ && git checkout ff58fa7e5a4f637a21d11daad0192683fe50ed15 && pip uninstall -y typing && pip install cpufeature && DS_BUILD_CPU_ADAM=1 DS_BUILD_SPARSE_ATTN=1 /tmp/DeepSpeed/install.sh -n && pip install typing`
> 
> `pip install transformers==3.5.1`

Я следовал строго блокноту, у меня установлены нужные версии : )

**Comment by Pro100rus32** [comment]
Я попытался прописать каждую команду отдельно, но я встретил ещё несколько ошибок:
![image](https://user-images.githubusercontent.com/64806740/120354575-37040900-c30b-11eb-8536-5b629a859548.png)
![image](https://user-images.githubusercontent.com/64806740/120354612-408d7100-c30b-11eb-8ba6-cb3dcffe6164.png)

**Comment by king-menin** [comment]
git clone https://github.com/microsoft/DeepSpeed.git завершился успешно?

**Comment by king-menin** [comment]
попробуйте вышеописанные команда записать в sh файл и запустить

**Comment by AlexanderKozhevin** [comment]
@king-menin @Pro100rus32 
Кому то удалось запустить блокнот?
Я дошел до этапа генерации, попробовать переустановить deepseed согласно описанию выше. Он нормально установился, но все же cuda выдает ошибку
```
RuntimeError: CUDA: Error- invalid ptx
```

<img width="1094" alt="Screenshot 2021-07-12 at 19 13 54" src="https://user-images.githubusercontent.com/4464561/125321393-4da77200-e345-11eb-8573-c208c071a686.png">

**Comment by Pro100rus32** [comment]
> @king-menin @Pro100rus32
> Кому то удалось запустить блокнот?
> Я дошел до этапа генерации, попробовать переустановить deepseed согласно описанию выше. Он нормально установился, но все же cuda выдает ошибку
> 
> ```
> RuntimeError: CUDA: Error- invalid ptx
> ```
> 
> <img alt="Screenshot 2021-07-12 at 19 13 54" width="1094" src="https://user-images.githubusercontent.com/4464561/125321393-4da77200-e345-11eb-8573-c208c071a686.png">

Нет. Этот репозиторий создан что бы просто быть, и говорить что они хорошие в своих постах на хабре. Мол выкладывают всё на гитхаб, это конечно хорошо, но только когда рядовой пользователь может это запустить, а не встретится чуть ли не с десятками ошибок которые пофиксить не в состояние. Я думаю стоит и дальше ждать, может всё таки они решат сами для начала проверить работоспособность блокнотов, и выпустить фикс.

Я уже не ожидаю решения этой проблемы, да и разбираться после нескольких ошибок - лень. Я молчу про то, что им лень через ctrl + f в коде поменять старую функцию на новую без других изменений, и исправить ошибку с новым PyTorch, чтоб не пришлось тратить время и юзать предустановленную библиотеку по дефолту а не качать несколько минут старый pytorch.

Советую лучше gpt-neo, они ещё новую версию со 175млрд вроде как выпустить собираются. И вот как раз у них - всё бесплатно, без СМС и регистрации.

**Comment by AlexanderKozhevin** [comment]
@Pro100rus32 не стоит так критично :)
как минимум gpt2 у них отлично запускается и до-тренировывается. 
А тут вообще ошибка от cuda.
