### ISSUE TITLE
CUDA: Error- invalid ptx

### ISSUE THREAD

**Issue by AlexanderKozhevin** [sberbank-ai/ru-gpts#68]
<img width="1130" alt="Screenshot 2021-07-12 at 19 08 35" src="https://user-images.githubusercontent.com/4464561/125320619-8f83e880-e344-11eb-867a-7554d34e0c6e.png">

**Comment by Artyrm** [comment]
I guess maybe it is connected with --fp16 use: https://github.com/openai/triton/issues/187#issuecomment-893563590
But I can't figure out still how to disable it in this example.

**Comment by Artyrm** [comment]
Yup.
If you're running ruGPT3XL_generate.ipynb just try to comment out this string in `ru_gpts/src/xl_wrapper.py`:
```
    # Fp16 conversion.
    model = FP16_Module(model)

    return model
```
Like that:
```
    # Fp16 conversion.
    # model = FP16_Module(model)

    return model
```
Worked for me.

From my understanding it is because of incompatibility of FP16 with some types of cards, to say Tesla P100 in my case.

**Comment by king-menin** [comment]
Add fixes for last updates on colab for rugpt3xl
