### ISSUE TITLE
Ошибка в Colab "Finetune_and_generate_RuGPTs_deepspeed_megatron.ipynb"

### ISSUE THREAD

**Issue by Artyrm** [sberbank-ai/ru-gpts#70]
После тренировки модели ни загрузить ни сконвертировать её не получается.

Очевидно, утилиты подразумевают другую структуру папок\файлов для checkpoints:

![image](https://user-images.githubusercontent.com/21180686/127330542-a6d68f62-6c70-46ec-b6c3-3855e40f5bc0.png)

**Comment by Artyrm** [comment]
И кстати  `!rm -rf ru-gpts` перед манипуляциями с обученной моделью выглядит странно. По идее это как раз удаление файлов, к которым идёт обращение дальше.

**Comment by Artyrm** [comment]
Обновление DeepSpeed до 0.4.3 (последняя) не помогло. Была некоторая надежда: https://github.com/microsoft/DeepSpeed/issues/507

**Comment by king-menin** [comment]
fixed
