### ISSUE TITLE
Notebook ruGPT3XL_generation.ipynb doesn't work, because of cuda 11.1

### ISSUE THREAD

**Issue by prohor33** [sberbank-ai/ru-gpts#78]
While running cell with:
`!sh setup.sh`
Output:
`RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 11.0.`
Cuda is 11.1

**Comment by king-menin** [comment]
Add fixes for last updates on colab for rugpt3xl

**Comment by prohor33** [comment]
@king-menin That's great! Thanks a lot!
