### ISSUE TITLE
support transformers  4.15.0

### ISSUE THREAD

**Issue by salaxieb** [sberbank-ai/ru-gpts#86]
Сделал дообучение sberbank-ai/rugpt2large на своих данных и хотел бы перенести в формат huggingface

но скрипт падает на одно из импортов:
```from transformers.tokenization_gpt2 import GPT2Tokenizer
ModuleNotFoundError: No module named 'transformers.tokenization_gpt2'
```

transformers.__version__
'4.15.0'

если откатиться на версию как в примере 3.5.0 то возникает следующая ошибка:
```from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler'
```

**Comment by king-menin** [comment]
попробуйте версию 3.5.1, если возникнет приведенная ошибка сделайте следующее
`!cp ru-gpts/src_utils/trainer_pt_utils.py /usr/local/lib/python3.7/dist-packages/transformers/trainer_pt_utils.py`

**Comment by 1LISA2** [comment]
![images (2)](https://user-images.githubusercontent.com/103248540/188130481-d49c8cfa-92b6-4060-abfc-eb5ee741cf68.jpeg)

**Comment by 1LISA2** [comment]
123456
